import assert from 'node:assert/strict';
import test from 'node:test';
import { readFileSync } from 'node:fs';
import { GuairaRespiros } from '../src/adventure/experimental/guaira/respiros/GuairaRespiros';
import { guairaRespirosBrowser } from './helpers/guairaRespirosHarness';
import { Canvas, Element } from './helpers/guairaLabHarness';
import recording from './helpers/guairaRespirosReplay.json';

test('Respiros entry uses three visible native controls, live return context and guarded explicit continuation', async t => {
    const h = guairaRespirosBrowser(t);
    const next = new Element(); next.id = 'respiros-boss'; next.tagName = 'A'; next.hidden = true;
    const get = h.document.getElementById;
    h.document.getElementById = id => id === next.id ? next : get(id);
    await import('../src/guaira-respiros');
    const game = h.window.worldGame as GuairaRespiros;
    assert.ok(game instanceof GuairaRespiros);
    assert.equal(h.exit.getAttribute('href'), './guaira.html?at=rice');
    assert.equal(next.hidden, true); assert.equal(h.pause.hidden, false);
    assert.equal(next.dispatch('click'), true, 'incomplete entry cannot skip to the corral');
    for (const control of [h.pause, h.retry, h.exit, next]) assert.equal((control.children[0] as Canvas).height, 44);
    h.run(game, recording.initialSettleFrames);
    for (const [count, keys] of recording.runs as [number, string[]][]) h.run(game, count, keys);
    assert.equal(game.finished, true); assert.equal(game.player.data.hasHelmet, true);
    h.exit.dispatch('click');
    assert.equal(h.exit.getAttribute('href'), './guaira.html?at=rice&visit=respiros-clear', 'live activation does not wait for toolbar RAF');
    h.pause.focus(); h.frame();
    assert.equal(next.hidden, false); assert.equal(h.pause.hidden, true); assert.equal(h.document.activeElement, next);
    assert.equal(next.dispatch('click'), false, 'finished route offers explicit corral entry');
    game.toggleRespirosPause(); h.frame();
    assert.equal(next.hidden, true); assert.equal(h.document.activeElement, h.pause);
    assert.equal(h.pause.getAttribute('aria-label'), 'Continuar');
    assert.equal(next.dispatch('click'), true, 'pause invalidates a queued continuation');
    assert.equal(h.exit.getAttribute('href'), './guaira.html?at=rice&visit=respiros-clear');
    h.retry.dispatch('click');
    assert.equal(game.finished, false); assert.equal(game.state, 'playing');
    assert.equal(h.exit.getAttribute('href'), './guaira.html?at=rice');
    assert.equal(next.dispatch('click'), true); assert.equal(game.store.save.checkpoint, null);
    assert.deepEqual(game.store.save.completed, []); assert.deepEqual(h.storageCalls, []);
    const html = readFileSync(new URL('../guaira-respiros.html', import.meta.url), 'utf8');
    assert.match(html, /guaira-touch-controls\.css/);
    assert.deepEqual(Array.from(html.matchAll(/<a\b[^>]*href="([^"]+)"/g), match => match[1]), ['./guaira-lab.html', './guaira.html?at=rice']);
});
