"""Camera-projected water geometry and occluded visible-water mask.
Load the .blend generated by build_guaira.py, then pass -- --output-dir DIR.
This separate Blender process never saves over the source scene.
"""
import bpy, json, os, sys, argparse
from mathutils import Vector
from bpy_extras.object_utils import world_to_camera_view

args = argparse.ArgumentParser()
args.add_argument('--output-dir', required=True)
options = args.parse_args(sys.argv[sys.argv.index('--')+1:] if '--' in sys.argv else [])
OUT = os.path.abspath(options.output_dir)
os.makedirs(OUT, exist_ok=True)
scene = bpy.context.scene
cam = scene.camera
if not cam or cam.data.type != 'ORTHO' or abs(cam.data.ortho_scale - 20.6) > 1e-5:
    raise RuntimeError('Expected the authored Guaíra orthographic camera')
W, H = 1920, 1200
bpy.context.view_layer.update()
def project(p):
    v = world_to_camera_view(scene, cam, Vector(p))
    return [round(v.x * W, 4), round((1-v.y)*H, 4)]
surfaces = []
for ob in scene.objects:
    if ob.type != 'MESH': continue
    if not any(m and m.name == 'Clean turquoise water' for m in ob.data.materials): continue
    verts = [ob.matrix_world @ v.co for v in ob.data.vertices]
    surfaces.append({'name':ob.name, 'vertices': [list(v) for v in verts],
                     'projected': [project(v) for v in verts],
                     'faces':[list(p.vertices) for p in ob.data.polygons]})
def emission(name, color):
    m=bpy.data.materials.new(name); m.use_nodes=True
    n=m.node_tree.nodes; n.clear(); e=n.new('ShaderNodeEmission'); e.inputs[0].default_value=(*color,1)
    o=n.new('ShaderNodeOutputMaterial'); m.node_tree.links.new(e.outputs[0],o.inputs[0]); return m
white=emission('PROOF visible water',(1,1,1)); black=emission('PROOF occluders',(0,0,0))
for ob in scene.objects:
    if ob.type in {'MESH','CURVE','SURFACE','META','FONT'}:
        iswater=any(m and m.name == 'Clean turquoise water' for m in ob.data.materials)
        ob.data.materials.clear(); ob.data.materials.append(white if iswater else black)
        if ob.type == 'MESH':
            for p in ob.data.polygons:p.material_index=0
scene.world.use_nodes=True
scene.world.node_tree.nodes['Background'].inputs[0].default_value=(0,0,0,1)
scene.world.node_tree.nodes['Background'].inputs[1].default_value=0
scene.render.engine='CYCLES'; scene.cycles.samples=12; scene.cycles.max_bounces=0
scene.cycles.use_denoising=False; scene.render.film_transparent=False
scene.render.resolution_x=W;scene.render.resolution_y=H;scene.render.resolution_percentage=100
scene.render.image_settings.file_format='PNG'; scene.render.image_settings.color_mode='BW'
scene.view_settings.view_transform='Standard';scene.view_settings.look='None';scene.view_settings.exposure=0;scene.view_settings.gamma=1
scene.render.filepath=OUT+'/water-mask-source.png'
origin=project((0,0,0)); basis={axis: project(p) for axis,p in [('x',(1,0,0)),('y',(0,1,0)),('z',(0,0,1))]}
json.dump({'sourceSize':[W,H], 'camera':{'location':list(cam.location),'rotation':list(cam.rotation_euler),'orthoScale':cam.data.ortho_scale},'projection':{'origin':origin,'basis':basis},'surfaces':surfaces},open(OUT+'/water-surfaces-source.json','w'),indent=2)
print('WATER_SURFACES',len(surfaces),[o['name'] for o in surfaces])
bpy.ops.render.render(write_still=True)
