import type { CoinApproach, ApproachVariant } from './naturalCoinApproach';
export interface NaturalCoinGuide extends CoinApproach {
    reference: ApproachVariant;
    /** Authored span along the real approach/traversal/landing, not an airtime ratio. */
    span: [number, number];
    /** Descending paths share their pickup corridor between walking and running. */
    sharedDescent?: boolean;
    intent: string;
}
const walk = { run: false, phaseFrames: 60 }, run = { run: true, phaseFrames: 0 };
export const CAMPAIGN_NATURAL_GUIDES: NaturalCoinGuide[] = [
    {stage:'1-1',name:'First gap from the real opening approach',firstCoin:4,count:7,entry:'spawn',prelude:[{x:248,hold:9}],jump:{x:424,hold:9},endX:536,endFeetY:224,reference:walk,span:[400,520],intent:'Ordinary walking hop; running can take off earlier with a shorter hold.'},
    {stage:'1-2',name:'First bridge from spawn',firstCoin:4,count:6,entry:'spawn',jump:{x:324,hold:9},endX:432,endFeetY:208,reference:walk,span:[304,416],intent:'Use the nearest intact bridge segment with a moderate walking hop.'},
    {stage:'1-2',name:'Second bridge after its patrol',firstCoin:10,count:6,entry:{x:528,feetY:208,source:'main bank before the minion'},prelude:[{x:544,hold:9}],jump:{x:720,hold:9},endX:832,endFeetY:192,reference:{...walk,phaseFrames:0},span:[700,816],intent:'Repeat the first bridge rhythm after clearing the patrol.'},
    {stage:'1-2',name:'Rising bridge crossing',firstCoin:16,count:7,entry:{x:1424,feetY:208,source:'wide bank before the third broken bridge'},jump:{x:1612,hold:9},endX:1760,endFeetY:176,reference:run,span:[1584,1744],intent:'A running hop clears the higher landing; walking needs more held height.'},
    {stage:'1-3',name:'Upper-route entrance from spawn',firstCoin:4,count:7,entry:'spawn',jump:{x:252,hold:9},endX:352,endFeetY:192,reference:walk,span:[232,336],intent:'The optional fast route begins at the actual lip, above the lower exploration route.'},
    {stage:'1-3',name:'Upper-route return from checkpoint',firstCoin:11,count:7,entry:{checkpoint:0},jump:{x:1084,hold:9},endX:1240,endFeetY:224,reference:run,span:[1064,1224],intent:'Use forward momentum to reach the next upper catwalk; the lower route remains separate.'},
    {stage:'1-4',name:'Two usable cliff steps',firstCoin:4,count:8,entry:'spawn',prelude:[{x:266,hold:9}],jump:{x:448,hold:9},followup:[{x:576,hold:9}],endX:656,endFeetY:160,reference:walk,span:[432,640],intent:'Land on the falling shelf, then make the separate 16px step up. The shelf now gives time to decide.'},
    {stage:'2-1',name:'Cargo stepping stone and onward hop',firstCoin:4,count:10,entry:{x:752,feetY:176,source:'cargo roof before its helmet patrol'},prelude:[{x:768,hold:9}],jump:{x:976,hold:9},endX:1104,endFeetY:208,reference:{...walk,phaseFrames:0},span:[872,1080],intent:'Drop onto the intermediate platform, then jump the remaining gap instead of demanding a maximal roof skip.'},
    {stage:'2-4',name:'Dispatch stepping-stone descent',firstCoin:14,count:10,entry:{x:1984,feetY:160,source:'dispatch roof after its patrol'},endX:2240,endFeetY:208,reference:walk,span:[2032,2224],sharedDescent:true,intent:'Walk or run down the two existing steps; a high jump is unnecessary.'},
    {stage:'3-2',name:'Readable optional maintenance hop',firstCoin:0,count:5,entry:{x:1752,feetY:128,source:'first optional maintenance catwalk'},jump:{x:1792,hold:9},endX:1880,endFeetY:112,reference:walk,span:[1776,1848],intent:'A controlled optional hop; keep its coins below the permanent HUD and leave the seal distinct.'},
    {stage:'3-4',name:'First pressure-room descent',firstCoin:4,count:10,entry:{x:832,feetY:160,source:'safe roof between the pressure jets'},endX:1104,endFeetY:224,reference:walk,span:[896,1088],sharedDescent:true,intent:'Observe the jet opening, then follow the descending surfaces without a gratuitous high jump.'},
    {stage:'3-4',name:'Second pressure-room descent',firstCoin:14,count:10,entry:{x:1872,feetY:144,source:'roof after the pressure-room enemy'},endX:2144,endFeetY:224,reference:walk,span:[1920,2128],sharedDescent:true,intent:'Follow the intermediate ledge and lower receiving floor.'},
    {stage:'5-1',name:'Cold-stock descent',firstCoin:4,count:10,entry:{x:464,feetY:192,source:'ice roof before the first descending gap'},endX:704,endFeetY:224,reference:walk,span:[512,688],sharedDescent:true,intent:'Keep the natural momentum across the two descending steps.'},
    {stage:'5-1',name:'Two-step cold-stock ascent',firstCoin:14,count:11,entry:{checkpoint:1},prelude:[{x:1536,hold:9}],jump:{x:1824,hold:9},followup:[{x:1928,hold:9}],endX:2000,endFeetY:144,reference:walk,span:[1808,1992],intent:'Use the intermediate landing before the separate 32px ascent; a one-tile extension prevents a braking trap.'},
    {stage:'5-4',name:'Two-step ice-roof ascent',firstCoin:4,count:10,entry:'spawn',prelude:[{x:240,hold:9}],jump:{x:528,hold:9},followup:[{x:632,hold:9}],endX:720,endFeetY:144,reference:walk,span:[512,704],intent:'Moderate first hop, stable braking shelf, then the separate 32px upward hop.'},
    {stage:'5-4',name:'Ice-roof descent',firstCoin:14,count:10,entry:{x:1840,feetY:144,source:'ice roof before its descending platforms'},endX:2112,endFeetY:224,reference:walk,span:[1888,2096],sharedDescent:true,intent:'Read the actual downward route, not an invisible maximum-height arc.'},
    {stage:'6-4',name:'Final high descent after the charger',firstCoin:4,count:11,entry:{x:912,feetY:128,source:'upper roof before the charger'},prelude:[{x:960,hold:9}],endX:1264,endFeetY:224,reference:{...walk,phaseFrames:0},span:[1080,1256],sharedDescent:true,intent:'Clear the charger, then descend the two real steps. No coin remains hidden above the HUD.'},
    {stage:'6-4',name:'Final bridge descent after the patrol',firstCoin:15,count:10,entry:{x:1952,feetY:144,source:'last roof before its helmet patrol'},prelude:[{x:1984,hold:9}],endX:2320,endFeetY:208,reference:{...walk,phaseFrames:0},span:[2112,2304],sharedDescent:true,intent:'Clear the patrol and follow the falling shelf down to the final bank.'},
    {stage:'1-1',name:'Lighthouse gap from the last checkpoint',firstCoin:19,count:6,entry:{checkpoint:1},prelude:[{x:2016,hold:9}],jump:{x:2220,hold:9},endX:2352,endFeetY:224,reference:walk,span:[2200,2328],intent:'Step up from the checkpoint, approach the actual edge, then make an ordinary descending hop.'},
    {stage:'1-4',name:'Long cliff stepping-stone sequence',firstCoin:12,count:9,entry:{x:1408,feetY:176,source:'wide upper bank before the long descent'},jump:{x:1496,hold:6},followup:[{x:1656,hold:12}],endX:1824,endFeetY:224,reference:run,span:[1472,1792],intent:'Use the centre of the falling shelf, then its separate onward jump; avoid landing on its last pixels.'},
    {stage:'2-3',name:'Container departure with real incoming momentum',firstCoin:4,count:7,entry:{x:432,feetY:176,source:'container roof before the departure edge'},jump:{x:492,hold:9},endX:672,endFeetY:224,reference:run,span:[464,624],intent:'A moderate running departure; the separate secret-shuttle ribbon stays unchanged.'},
    {stage:'2-4',name:'Cargo descent after the charger',firstCoin:4,count:10,entry:{x:784,feetY:144,source:'high roof before the charger'},prelude:[{x:800,hold:9}],jump:{x:960,hold:9},endX:1160,endFeetY:224,reference:run,span:[944,1144],intent:'Clear the charger, then use a moderate running jump from the real departure lip.'},
    {stage:'3-1',name:'Receiving-belt departure from spawn',firstCoin:4,count:7,entry:'spawn',prelude:[{x:272,hold:9},{x:360,hold:9}],jump:{x:512,hold:9},endX:672,endFeetY:224,reference:run,span:[488,648],intent:'Approach against the conveyor and clear the launcher before departing to the receiving floor.'},
    {stage:'3-1',name:'Tank departure from the checkpoint',firstCoin:11,count:9,entry:{checkpoint:0},prelude:[{x:896,hold:12},{x:992,hold:9}],jump:{x:1132,hold:9},endX:1328,endFeetY:224,reference:run,span:[1104,1304],intent:'The roof patrol and the gap are distinct jumps, followed by a stable belt landing.'},

];
export const naturalGuideKey = (p: Pick<CoinApproach, 'stage' | 'firstCoin'>) => `${p.stage}:c${p.firstCoin}`;
