import { writeFileSync } from 'node:fs';
import { STAGES } from '../src/adventure/campaign';
import { CAMPAIGN_JUMP_PLANS } from './lib/campaignJumpPlans';
import { traceJump, traceCarrierRide, sampleJumpCoins, collectedOnTrace } from './lib/jumpCoinTrajectory';
import baseline from '../tests/fixtures/campaign-pickups-before-jump-coins.json';

const generated: Record<string, [string, number, number][]> = {};
for (const plan of CAMPAIGN_JUMP_PLANS) {
    const stage = STAGES.find(s => s.id === plan.stage)!;
    const trace = 'carrier' in plan.witness ? traceCarrierRide(stage, plan.witness) : traceJump(stage, plan.witness);
    const end = trace.frames.at(-1)!, [left, right, feet] = plan.landing;
    if (!trace.launchGrounded || !trace.landed || trace.dead || trace.hazardContact || trace.landingFeet !== feet || end.x < left || end.x + end.width > right)
        throw new Error(`${plan.stage} ${plan.name}: invalid trace ${JSON.stringify({ launch: trace.launchGrounded, end, feet: trace.landingFeet })}`);
    const ids = new Set(Array.from({ length: plan.count }, (_, i) => `${plan.stage}:c${plan.firstCoin + i}`));
    const old = (baseline as Record<string, (string | number)[][]>)[plan.stage]
        .filter(p => ids.has(String(p[0]))).map(p => ({ x: Number(p[2]), y: Number(p[3]) }));
    const points = sampleJumpCoins(trace, plan.count, plan.endTrim);
    (generated[plan.stage] ??= []).push(...points.map((p, i): [string, number, number] => [`${plan.stage}:c${plan.firstCoin + i}`, p.x, p.y]));
    console.log(`${plan.stage} ${plan.name}: ${collectedOnTrace(trace, old)}/${plan.count} → ${collectedOnTrace(trace, points)}/${plan.count}; launch (${trace.frames[0].x.toFixed(1)},${(trace.frames[0].y + trace.frames[0].height).toFixed(0)}), landing (${end.x.toFixed(1)},${trace.landingFeet}), ${trace.frames.length - 1} frames, rise ${trace.rise.toFixed(1)} px`);
}
if (process.argv.includes('--write')) {
    const source = Object.entries(generated).map(([stage, points]) => `    '${stage}': [\n${points.map(p => `        ${JSON.stringify(p)},`).join('\n')}\n    ],`).join('\n');
    writeFileSync('src/adventure/campaignJumpCoins.ts', `/** Generated by scripts/audit_jump_coins.ts --write from real Player/WorldLevel traces.\n * Keep pickup IDs: only coordinates change, after existing route-cue allocation. */\nexport const CAMPAIGN_JUMP_COINS: Readonly<Record<string, readonly (readonly [string, number, number])[]>> = {\n${source}\n};\n`);
}
