/* Real input and focused arranged combat cases in an isolated browser profile.
 * Supply PLAYWRIGHT_LIB and CHROMIUM_PATH; this does not install dependencies. */
const {chromium} = require(process.env.PLAYWRIGHT_LIB || 'playwright');
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const base = process.env.DELICIA_URL || 'http://127.0.0.1:3030';
const out = path.resolve(process.env.DELICIA_OUTPUT || 'output/delicia/v2');
fs.mkdirSync(out, {recursive:true});
const report={url:base,checks:[],errors:[],screenshots:[],arrangedCases:[]};
const check=(name,data)=>report.checks.push({name,...data});
(async()=>{
  const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH});
  try {
    const context=await browser.newContext({viewport:{width:1440,height:900}});
    const page=await context.newPage();
    page.on('pageerror',e=>report.errors.push(e.message));
    page.on('response',r=>{if(r.status()>=400&&r.url().includes('/assets/delicia/'))report.errors.push(`${r.status()} ${r.url()}`);});
    const shot=async(name)=>{await page.screenshot({path:path.join(out,name+'.png'),fullPage:true});report.screenshots.push(name+'.png');};
    await page.goto(base+'/delicia.html');
    await page.waitForFunction(()=>window.deliciaGame?.art.images.size===13);
    await page.getByRole('button',{name:'Jogar',exact:true}).waitFor();
    await shot('title');
    await page.getByRole('button',{name:'Jogar',exact:true}).click();
    await page.getByRole('heading',{name:'Cais do Primeiro Gole',exact:true}).waitFor();
    assert.equal(await page.locator('.dl-pin').count(),12);
    check('Native map has twelve pins and first stage is available',{});
    await page.waitForFunction(()=>!!window.deliciaGame.audio.musicSource);
    check('Original music decodes and starts after the user gesture',{});
    const audioNames=fs.readdirSync('public/assets/delicia/audio').filter(n=>n.endsWith('.ogg')).map(n=>n.slice(0,-4));
    const decoded=await page.evaluate(async names=>Promise.all(names.map(async name=>({name,seconds:(await window.deliciaGame.audio.load(name))?.duration}))),audioNames);
    assert.ok(decoded.length===20&&decoded.every(a=>a.seconds>0));
    check('All twenty shipped Opus clips decode successfully',{clips:decoded.length});
    await page.keyboard.press('m');await page.waitForTimeout(120);
    const mute=await page.evaluate(()=>({muted:window.deliciaGame.audio.muted,gain:window.deliciaGame.audio.masterGain.gain.value,state:window.deliciaGame.audio.context.state}));
    check('Mute output state',mute);assert.ok(mute.muted&&mute.gain<.01);
    await page.keyboard.press('m');
    check('Mute silences the common output for music, ambience, speech and effects',{});
    await shot('map');
    await page.getByRole('button',{name:'Jogar',exact:true}).click();
    await page.getByRole('button',{name:'Pular',exact:true}).click();
    await page.waitForFunction(()=>window.deliciaGame.sim.player.grounded);
    const before=await page.evaluate(()=>({x:window.deliciaGame.sim.player.x,y:window.deliciaGame.sim.player.y}));
    await page.keyboard.down('ArrowRight');
    await page.keyboard.down('Space');
    await page.waitForTimeout(180);
    const jumped=await page.evaluate(()=>({x:window.deliciaGame.sim.player.x,y:window.deliciaGame.sim.player.y}));
    await page.keyboard.up('Space');await page.keyboard.up('ArrowRight');
    assert.ok(jumped.x>before.x+10&&jumped.y<before.y-35);
    check('Physical keyboard moves and jumps', {before,jumped});
    await page.keyboard.press('Escape');
    const paused=await page.evaluate(()=>window.deliciaGame.sim.elapsed);
    await page.waitForTimeout(250);
    assert.equal(await page.evaluate(()=>window.deliciaGame.sim.elapsed),paused);
    await page.getByRole('button',{name:'Opções',exact:true}).click();
    await page.getByText('Controles',{exact:true}).click();
    assert.equal(await page.locator('.dl-controls-table tbody tr').count(),8);
    await page.keyboard.press('Escape');
    await page.getByRole('heading',{name:'Pausa',exact:true}).waitFor();
    assert.equal(await page.evaluate(()=>window.deliciaGame.sim.elapsed),paused);
    await page.getByRole('button',{name:'Memórias',exact:true}).click();
    assert.equal(await page.locator('.dl-lore-entry').count(),await page.evaluate(()=>window.deliciaGame.store.save.lore.length));
    await page.getByRole('button',{name:'Voltar',exact:true}).click();
    await page.getByRole('heading',{name:'Pausa',exact:true}).waitFor();
    assert.equal(await page.evaluate(()=>window.deliciaGame.sim.elapsed),paused);
    check('Settings and journal return to pause without resetting or advancing the run',{});
    await page.getByRole('button',{name:'Continuar',exact:true}).click();
    check('Pause freezes simulation and the native button resumes it',{});
    await page.waitForFunction(()=>window.deliciaGame.sim.player.grounded);
    await shot('harbor');
    await page.keyboard.down('ArrowRight');
    await page.waitForFunction(()=>window.deliciaGame.sim.player.health<4,{},{timeout:6000});
    await page.keyboard.up('ArrowRight');
    const gap=await page.evaluate(()=>({health:window.deliciaGame.sim.player.health,x:window.deliciaGame.sim.player.x,message:document.querySelector('.dl-status').textContent}));
    assert.ok(gap.x<420&&gap.message.includes('gap'));
    check('Walking into a real terrain gap costs a heart and returns Feka to safety',gap);
    await shot('feka-gap');
    await page.keyboard.press('Escape');
    const checkpoint=await page.evaluate(()=>{
      const app=window.deliciaGame,sim=app.sim,cp=sim.stage.checkpoints[0];
      sim.player.x=cp.x;sim.player.y=cp.y;sim.player.vx=0;sim.player.vy=0;sim.valves.add('v5');
      app.step(1/120,{left:false,right:false,jump:false,jumpPressed:false,jumpReleased:false,dash:false,pound:false,seed:false,parry:false,interact:false});
      return app.store.save.checkpoint;
    });
    assert.equal(checkpoint.index,0);assert.ok(checkpoint.valves.includes('v5'));
    report.arrangedCases.push('Checkpoint contact uses the real simulation with an arranged position; then reload verifies persisted valves.');
    await page.reload();
    await page.getByRole('button',{name:'Continuar',exact:true}).click();
    await page.getByRole('button',{name:'Jogar',exact:true}).click();
    await page.getByRole('button',{name:'Pular',exact:true}).click();
    const restored=await page.evaluate(()=>({checkpoint:window.deliciaGame.sim.checkpoint,valves:[...window.deliciaGame.sim.valves]}));
    assert.equal(restored.checkpoint,0);assert.ok(restored.valves.includes('v5'));
    check('Reload restores checkpoint and opened valves',restored);
    await page.evaluate(async()=>{
      const app=window.deliciaGame,{completeDeliciaStage}=await import('/src/adventure/delicia/DeliciaProgress.ts'),{DELICIA_STAGES}=await import('/src/adventure/delicia/DeliciaContent.ts');
      for(const s of DELICIA_STAGES)completeDeliciaStage(app.store.save,s.id,100);
      app.store.persist();app.loadStage('delicia-6',true);
    });
    await page.waitForFunction(()=>window.deliciaGame.sim.boss.beat==='tell');
    await shot('jaja');
    await page.evaluate(()=>window.deliciaGame.loadStage('delicia-12',true));
    await page.waitForFunction(()=>window.deliciaGame.sim.boss.gaps.length>0);
    const guinaGap=await page.evaluate(()=>{
      const app=window.deliciaGame,sim=app.sim,gap=sim.boss.gaps[0];app.pause();
      sim.player.x=gap.x+40;sim.player.y=396;sim.player.invincible=0;const hp=sim.player.health;
      app.step(1/120,{left:false,right:false,jump:false,jumpPressed:false,jumpReleased:false,dash:false,pound:false,seed:false,parry:false,interact:false});
      return {gap:{x:gap.x,w:gap.w},healthBefore:hp,healthAfter:sim.player.health,respawnX:sim.player.x};
    });
    assert.equal(guinaGap.healthAfter,guinaGap.healthBefore-1);assert.ok(guinaGap.respawnX<340);
    check('Guina opens an actual collision gap, which costs health and respawns Feka',guinaGap);
    report.arrangedCases.push('Player positioned inside an already naturally spawned Guina gap to verify collision.');
    await page.evaluate(()=>{const app=window.deliciaGame;app.resume();app.sim.player.x=650;app.sim.player.y=396;app.sim.cameraX=350;app.sim.boss.beat='tell';app.sim.boss.attack='gap';app.sim.boss.target={x:570,y:450,w:180,h:450};app.sim.boss.timer=1;});
    await shot('guina');
    report.arrangedCases.push('Guina screenshot frames a warning pose; it is a staged visual review, not a completed playthrough.');
    await page.evaluate(()=>window.deliciaGame.showMap());
    assert.equal(await page.locator('.dl-stage-row').count(),0);
    await shot('map-complete-preview');
    await page.getByRole('button',{name:'Fases',exact:true}).click();
    assert.equal(await page.locator('.dl-stage-row').count(),14);
    await page.keyboard.press('Escape');
    await page.getByRole('button',{name:'Menu',exact:true}).click();
    await page.getByRole('button',{name:'Opções',exact:true}).click();
    await page.getByLabel('Reduzir movimento',{exact:true}).check();
    const reduced=await page.evaluate(()=>window.deliciaGame.store.save.reducedMotion);assert.ok(reduced);
    check('Reduced motion control persists and optional destinations are exposed',{});
    await shot('settings');
    const assets=await page.evaluate(()=>({decoded:[...window.deliciaGame.audio.buffers.keys()],images:[...window.deliciaGame.art.images.keys()]}));
    check('Assets loaded',assets);
    await page.goto(base+'/?delicia=true');
    await page.waitForFunction(()=>!!window.deliciaGame);
    assert.equal(await page.locator('#game-canvas:visible').count(),0);
    check('Query entry hides the base canvas and starts the expansion',{});
    await page.goto(base+'/');await page.waitForFunction(()=>!!window.worldGame);
    await page.evaluate(()=>window.worldGame.toMap());
    await page.locator('.world-map-delicia').waitFor();
    await page.getByRole('button',{name:'Ver panorama',exact:true}).click();
    await page.waitForFunction(()=>!!window.worldGame.mapView.deliciaImage);
    await page.waitForTimeout(1200);
    const framed=await page.evaluate(async()=>{
      const view=window.worldGame.mapView,{mapToScreen}=await import('/src/adventure/WorldMapModel.ts'),{DELICIA_ATLAS:a}=await import('/src/adventure/delicia/DeliciaIsland.ts');
      return {left:mapToScreen({x:a.left,y:a.top},view.camera),right:mapToScreen({x:a.left+a.widthInMap,y:a.top+a.heightInMap},view.camera),width:view.width,height:view.height};
    });
    assert.ok(framed.left.x>=0&&framed.right.x<=framed.width&&framed.left.y>=0&&framed.right.y<=framed.height);
    check('The panorama camera fits the complete fixed expansion footprint',framed);
    await shot('world-atlas');
    const integrated=await page.evaluate(()=>({visible:!window.worldGame.mapView.deliciaPin.hidden,href:window.worldGame.mapView.deliciaPin.getAttribute('href')}));
    assert.ok(integrated.visible);assert.equal(integrated.href,'./delicia.html');
    await page.locator('.world-map-delicia').click();
    await page.waitForFunction(()=>!!window.deliciaGame);
    check('The released World panorama shows the giant island and its native link enters the expansion',integrated);
    const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
    const mp=await mobile.newPage();mp.on('pageerror',e=>report.errors.push('mobile: '+e.message));
    await mp.goto(base+'/delicia.html');await mp.waitForFunction(()=>window.deliciaGame?.art.images.size===13);
    await mp.getByRole('button',{name:'Jogar',exact:true}).click();
    await mp.screenshot({path:path.join(out,'mobile-map.png'),fullPage:true});report.screenshots.push('mobile-map.png');
    await mp.getByRole('button',{name:'Jogar',exact:true}).click();
    await mp.getByRole('button',{name:'Pular',exact:true}).click();
    check('Mobile control state',{state:await mp.evaluate(()=>({screen:window.deliciaGame.screen,hidden:window.deliciaGame.touch.hidden,display:getComputedStyle(window.deliciaGame.touch).display,coarse:matchMedia('(pointer:coarse)').matches}))});
    assert.equal(await mp.locator('.dl-touch-button:visible').count(),8);
    const target=mp.getByRole('button',{name:'Pular',exact:true});
    await mp.waitForFunction(()=>window.deliciaGame.sim.player.grounded);
    const touchBox=await target.boundingBox(),cdp=await mobile.newCDPSession(mp);
    await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:touchBox.x+15,y:touchBox.y+15}]});
    await mp.waitForTimeout(180);
    assert.ok(await mp.evaluate(()=>window.deliciaGame.sim.player.y<365));
    await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
    const noOverflow=await mp.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1);assert.ok(noOverflow);
    await mp.screenshot({path:path.join(out,'mobile-game.png'),fullPage:true});report.screenshots.push('mobile-game.png');
    check('Mobile exposes eight touch controls without horizontal overflow',{});
    await mobile.close();await context.close();
    assert.deepEqual(report.errors,[]);
    report.passed=true;
  } finally {await browser.close();fs.writeFileSync(path.join(out,'browser-report.json'),JSON.stringify(report,null,2));}
})().catch(e=>{console.error(e.stack);process.exitCode=1;});
