from pathlib import Path
import json,argparse,hashlib
p=argparse.ArgumentParser();p.add_argument('--output-dir',required=True);a=p.parse_args();out=Path(a.output_dir);root=Path(__file__).resolve().parent
read=lambda n:json.load(open(out/n));phases=[];passed=True
for phase in [0,1]:
 physical=read(f'serra-audit-physical-phase{phase}.json');head=read(f'serra-audit-head-phase{phase}.json');raster=read(f'serra-audit-raster-phase{phase}.json');bill=read(f'serra-audit-billboard-phase{phase}.json')
 counts={k:sum(x['phaseAvailable'] and (k!='walkSurfaceMismatches' or x['movement']=='walk') for x in physical[k]) for k in ['unsupportedFeet','headroomObstructions','walkSurfaceMismatches']};counts['floatingTimberAnchors']=physical['floatingTimberAnchorCount']
 profiles=[{'profile':x['profile'],'headContacts':sum(x['activeHeadContactsByObject'].values()),'faceContacts':sum(x['activeFaceContactsByObject'].values()),'newBodyContacts':sum(v for k,v in x['bodyContactsByObject'].items() if k.startswith('enrich_'))} for x in raster['profiles']]
 newcontacts=[x for x in bill['contacts'] if x['object'].startswith('enrich_') and x['phaseAvailable'] and x['pixelRelativeToFoot'][1]>2]
 ok=not any(counts.values()) and head['passed'] and not newcontacts and all(not x['headContacts'] and not x['faceContacts'] and not x['newBodyContacts'] for x in profiles);passed &=ok
 phases.append({'phase':phase,'passed':ok,'activePhysicalCounts':counts,'sourceHeadFacePassed':head['passed'],'newSourceBodyContacts':len(newcontacts),'raster':profiles,'routeSamples':physical['routeSampleCount'],'supportRays':physical['supportRayCount'],'spriteSourceRays':bill['rayCount']})
cabins=read('serra-audit-cabins-cabins.json');sweep=read('serra-audit-cabins-continuous-cabins.json');rider=read('serra-audit-rider-rider-source.json');rr=read('serra-audit-rider-raster-rider.json');inv=read('independent-invariants.json');enrich=read('serra-enrichment-audit.json')
rsource=all(not x['intervals']['anyHead'] and not x['intervals']['anyFaceSkin'] for x in rider['lanes']);raster_ok=all(not x['headContactPoses'] and not x['faceContactPoses'] for x in rr['results']);passed &=rsource and raster_ok and cabins['collisionPoseObjectCount']==0 and sweep['contactCount']==0 and cabins['pairCrossing']['passed'] and inv['passed']
report={'status':'PASS' if passed else 'BLOCKED','scope':'Frozen original geometry and metadata; active walking/boarding approaches both phases; full original Feka head/face and new-geometry body occlusion; both maintenance cabins and riders, both directions; conservative passenger-exit body/screen corridor. Integration/browser gate remains separate.','originalGeometry':inv,'stationaryPhases':phases,'maintenancePhysical':{'poses':cabins['poseCount'],'collisions':cabins['collisionPoseObjectCount'],'continuousHullCount':sweep['hullCount'],'continuousContacts':sweep['contactCount'],'pairCrossing':cabins['pairCrossing']},'movingRider':{'sourcePassed':rsource,'roundedRasterPassed':raster_ok,'samplesPerLane':rider['lanes'][0]['sampleCount'],'profiles':[{k:x[k] for k in ['profile','lane','sampleCount','headContactPoses','faceContactPoses']} for x in rr['results']]},'addedGeometryPreflight':{'rays':enrich['preflightConservativeRays'],'includesPassengerExit':True,'removedGroups':enrich['removedGroups']},'render':{'size':[1920,1200],'samples':128,'denoise':False,'newFullSizeOverlays':0,'baseReplacement':True},'limitations':['Existing low body contacts with maintenance cabin panels and one foreground support remain from the approved scene; do not claim complete full-body visibility.','Dense rider samples use .0005 progress, 2001 poses per lane; physical hull sweep is continuous but visibility is sampled.','Raster profiles remain desktop1180x757 zoom1, portrait400x606 zoom1.05, landscape846x392 zoom1; runtime pan/zoom integration is owned by the integrator.','No independent browser or Oracle actions were performed.'],'sourceSha256':hashlib.sha256((root/'enrich_serra.py').read_bytes()).hexdigest(),'blendSha256':hashlib.sha256((out/'serra-enriched.blend').read_bytes()).hexdigest()};(out/'validation-summary.json').write_text(json.dumps(report,indent=2)+'\n');print(json.dumps(report,indent=2));assert passed
